=== alexmemory/spicy/spicyEngine/misc/resources/dblp/dblp.xsd
<?xml version="1.0"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="dblp">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="articles" minOccurs="0" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="article" nillable="true">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" name="title" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="pages" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="year" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="volume" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="journal" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="number" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="ee" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="url" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="cdrom" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="editor" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="month" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="publisher" nillable="true" type="xs:string"/>
										<xs:element name="authors" minOccurs="0" nillable="true">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" minOccurs="0" name="author" nillable="true">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="authorId" nillable="true" type="xs:string"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="authors" minOccurs="0" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="author" nillable="true">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" name="id" nillable="true" type="xs:string"/>
										<xs:element minOccurs="0" name="name" nillable="true" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alexmemory/spicy/spicyEngine/misc/resources/dblp/dblpOriginal-small.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<dblp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dblp.xsd">
    <articles>     
        <article key="journals/eik/HupbachR83" mdate="2003-06-30">
            <author>Ulrich L. Hupbach</author>
            <author>Horst Reichel</author>
            <title/>
            <pages>297-305</pages>
            <year>1983</year>
            <volume>19</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>6</number>
            <url>db/journals/eik/eik19.html#HupbachR83</url>
        </article>
        <article key="journals/eik/Shyamasundar78" mdate="2003-06-30">
            <author>R. K. Shyamasundar</author>
            <title/>
            <pages>361-376</pages>
            <year>1978</year>
            <volume>14</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>7/8</number>
            <url>db/journals/eik/eik14.html#Shyamasundar78</url>
        </article>
        <article key="journals/eik/BornerPG85" mdate="2003-07-07">
            <author>Ferdinand Borner</author>
            <author>Reinhard Poschel</author>
            <author>Michael Gussel</author>
            <title/>
            <pages>331-342</pages>
            <year>1985</year>
            <volume>21</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>7/8</number>
            <url>db/journals/eik/eik21.html#BornerPG85</url>
        </article>
        <article key="journals/eik/FrankeK77" mdate="2003-06-30">
            <author>Gunter Franke</author>
            <author>Manfred Koegst</author>
            <title/>
            <pages>281-294</pages>
            <year>1977</year>
            <volume>13</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>6</number>
            <url>db/journals/eik/eik13.html#FrankeK77</url>
        </article>
        <article key="journals/eik/Franken66" mdate="2003-06-16">
            <author>Peter Franken</author>
            <title/>
            <pages>223-233</pages>
            <year>1966</year>
            <volume>2</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>4</number>
            <url>db/journals/eik/eik2.html#Franken66</url>
        </article>
        <article key="journals/eik/Franken68" mdate="2003-06-16">
            <author>Peter Franken</author>
            <title/>
            <pages>197-204</pages>
            <year>1968</year>
            <volume>4</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>3</number>
            <url>db/journals/eik/eik4.html#Franken68</url>
        </article>
        <article key="journals/eik/Fischer77" mdate="2003-06-30">
            <author>Thomas R. M. Fischer</author>
            <title/>
            <pages>125-135</pages>
            <year>1977</year>
            <volume>13</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>3</number>
            <url>db/journals/eik/eik13.html#Fischer77</url>
        </article>
        <article key="journals/eik/Fischer89" mdate="2003-07-07">
            <author>Thomas Fischer</author>
            <title/>
            <pages>233-238</pages>
            <year>1989</year>
            <volume>25</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>5/6</number>
            <url>db/journals/eik/eik25.html#Fischer89</url>
        </article>
        <article key="journals/eik/Sonntag87a" mdate="2003-07-07">
            <author>Martin Sonntag</author>
            <title/>
            <pages>323-329</pages>
            <year>1987</year>
            <volume>23</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>7</number>
            <url>db/journals/eik/eik23.html#Sonntag87a</url>
        </article>
        <article key="journals/eik/Sonntag91a" mdate="2003-07-14">
            <author>Martin Sonntag</author>
            <title/>
            <pages>385-386</pages>
            <year>1991</year>
            <volume>27</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>7</number>
            <url>db/journals/eik/eik27.html#Sonntag91a</url>
        </article>
        <article key="journals/eik/QuynhK79" mdate="2003-06-30">
            <author>Nguyen Xuan Quynh</author>
            <author>Edward Kacki</author>
            <title/>
            <pages>279-300</pages>
            <year>1979</year>
            <volume>15</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>5/6</number>
            <url>db/journals/eik/eik15.html#QuynhK79</url>
        </article>
        <article key="journals/eik/ModrowG73a" mdate="2003-06-30">
            <author>Heinz D. Modrow</author>
            <author>Michael Gossel</author>
            <title/>
            <pages>549-567</pages>
            <year>1973</year>
            <volume>9</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>9</number>
            <url>db/journals/eik/eik9.html#ModrowG73a</url>
        </article>
        <article key="journals/eik/EhrichSS90" mdate="2003-07-07">
            <author>Hans-Dieter Ehrich</author>
            <author>Amilcar Sernadas</author>
            <author>Cristina Sernadas</author>
            <title/>
            <pages>33-48</pages>
            <year>1990</year>
            <volume>26</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>1/2</number>
            <url>db/journals/eik/eik26.html#EhrichSS90</url>
        </article>
        <article key="journals/eik/DisneyF82" mdate="2003-06-30">
            <author>Ralph L. Disney</author>
            <author>Peter Franken</author>
            <title/>
            <pages>595-602</pages>
            <year>1982</year>
            <volume>18</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>10/11</number>
            <url>db/journals/eik/eik18.html#DisneyF82</url>
        </article>
        <article key="journals/eik/HendrichS92" mdate="2003-07-14">
            <author>U. Hendrich</author>
            <author>Michael Stiebitz</author>
            <title/>
            <pages>113-125</pages>
            <year>1992</year>
            <volume>28</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>3</number>
            <url>db/journals/eik/eik28.html#HendrichS92</url>
        </article>
        <article key="journals/eik/SlotB85" mdate="2003-07-07">
            <author>Cees F. Slot</author>
            <author>Peter van Emde Boas</author>
            <title/>
            <pages>246-253</pages>
            <year>1985</year>
            <volume>21</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>4/5</number>
            <url>db/journals/eik/eik21.html#SlotB85</url>
        </article>
        <article key="journals/eik/LeschLS80" mdate="2003-06-30">
            <author>Jurgen Lesch</author>
            <author>Manfred Lesch</author>
            <author>Irmgard Schmeichel</author>
            <title/>
            <pages>63-68</pages>
            <year>1980</year>
            <volume>16</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>1-3</number>
            <url>db/journals/eik/eik16.html#LeschLS80</url>
        </article>
        <article key="journals/eik/Gerber70a" mdate="2003-06-16">
            <author>Siegmar Gerber</author>
            <title/>
            <pages>325-339</pages>
            <year>1970</year>
            <volume>6</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>6</number>
            <url>db/journals/eik/eik6.html#Gerber70a</url>
        </article>
        <article key="journals/eik/GerberH85" mdate="2003-07-07">
            <author>Siegmar Gerber</author>
            <author>Harald Hoyer</author>
            <title/>
            <pages>385-400</pages>
            <year>1985</year>
            <volume>21</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>7/8</number>
            <url>db/journals/eik/eik21.html#GerberH85</url>
        </article>
        <article key="journals/eik/GerberS76" mdate="2003-06-30">
            <author>Siegmar Gerber</author>
            <author>Holger Schackert</author>
            <title/>
            <pages>415-420</pages>
            <year>1976</year>
            <volume>12</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>8/9</number>
            <url>db/journals/eik/eik12.html#GerberS76</url>
        </article>
        <article key="journals/eik/Mecke66" mdate="2003-06-16">
            <author>Joseph Mecke</author>
            <title/>
            <pages>83-94</pages>
            <year>1966</year>
            <volume>2</volume>
            <journal>Elektronische Informationsverarbeitung und Kybernetik</journal>
            <number>2</number>
            <url>db/journals/eik/eik2.html#Mecke66</url>
        </article>
