=== alexmemory/spicy/spicyEngine/misc/resources/childrenDBKidsPresentsDB/childrenDB.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="childrenDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" name="children" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="child" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="childId" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="childName" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="age" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="motherRefId" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="motherRefName" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="fatherRefId" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="fatherRefName" nillable="true" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="parents" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="parent" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="parentId" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="parentName" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="affiliation" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="salary" nillable="true" type="xs:float"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="xmasBoxes" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="xmasBox" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="toy" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="giveRef" nillable="true" type="xs:int"/>
                    <xs:element minOccurs="1" name="receiveRef" nillable="true" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="phoneNumbers" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="phoneNumber" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="type" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="number" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="parentRefId" nillable="true" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="SBPS" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="schedule" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="location" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="time" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="childRef" nillable="true" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath=".//parent"/>
      <xs:field xpath="parentId"/>
      <xs:field xpath="parentName"/>
    </xs:key>
    <xs:key name="key2">
      <xs:selector xpath=".//child"/>
      <xs:field xpath="childId"/>
    </xs:key>
    <xs:key name="key3">
      <xs:selector xpath=".//child"/>
      <xs:field xpath="childId"/>
    </xs:key>
    <xs:keyref name="keyRef1" refer="key1">
      <xs:selector xpath=".//child"/>
      <xs:field xpath="fatherRefId"/>
      <xs:field xpath="fatherRefName"/>
    </xs:keyref>
    <xs:keyref name="keyRef2" refer="key2">
      <xs:selector xpath=".//xmasBox"/>
      <xs:field xpath="giveRef"/>
    </xs:keyref>
    <xs:keyref name="keyRef3" refer="key2">
      <xs:selector xpath=".//xmasBox"/>
      <xs:field xpath="receiveRef"/>
    </xs:keyref>
    <xs:keyref name="keyRef4" refer="key1">
      <xs:selector xpath=".//child"/>
      <xs:field xpath="fatherRefId"/>
      <xs:field xpath="fatherRefName"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== alexmemory/spicy/spicyEngine/misc/resources/childrenDBKidsPresentsDB/childrenDB-instance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<childrenDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="childrenDB.xsd">
  <children>
    <child>
      <childId>1</childId>
      <childName>Kyle</childName>
      <age>2</age>
      <motherRefId>201</motherRefId>
      <motherRefName>Anne</motherRefName>
      <fatherRefId>202</fatherRefId>
      <fatherRefName>Paul</fatherRefName>
    </child>
    <child>
      <childId>2</childId>
      <childName>Maya</childName>
      <age>4</age>
      <motherRefId>203</motherRefId>
      <motherRefName>Jill</motherRefName>
      <fatherRefId>204</fatherRefId>
      <fatherRefName>Mike</fatherRefName>
    </child>
    <child>
      <childId>3</childId>
      <childName>Eric</childName>
      <age>5</age>
      <motherRefId>205</motherRefId>
      <motherRefName>Sue</motherRefName>
      <fatherRefId>206</fatherRefId>
      <fatherRefName>Joe</fatherRefName>
    </child>
    <child>
      <childId>4</childId>
      <childName>Carmen</childName>
      <age>10</age>
      <motherRefId>205</motherRefId>
      <motherRefName>Sue</motherRefName>
      <fatherRefId>206</fatherRefId>
      <fatherRefName>Joe</fatherRefName>
    </child>
    <child>
      <childId>9</childId>
      <childName>Ben</childName>
      <age>6</age>
      <motherRefId>NULL</motherRefId>
      <motherRefName>NULL</motherRefName>
      <fatherRefId>NULL</fatherRefId>
      <fatherRefName>NULL</fatherRefName>
    </child>
  </children>
  <parents>
    <parent>
      <parentId>201</parentId>
      <parentName>Anne</parentName>
      <affiliation>Safeway</affiliation>
      <salary>50000</salary>
    </parent>
    <parent>
      <parentId>202</parentId>
      <parentName>Paul</parentName>
      <affiliation>IBM</affiliation>
      <salary>60000</salary>
    </parent>
    <parent>
      <parentId>203</parentId>
      <parentName>Jill</parentName>
      <affiliation>Xerox</affiliation>
      <salary>65000</salary>
    </parent>
    <parent>
      <parentId>204</parentId>
      <parentName>Mike</parentName>
      <affiliation>NASA</affiliation>
      <salary>45000</salary>
    </parent>
    <parent>
      <parentId>205</parentId>
      <parentName>Sue</parentName>
      <affiliation>MGM</affiliation>
      <salary>56000</salary>
    </parent>
    <parent>
      <parentId>206</parentId>
      <parentName>Joe</parentName>
      <affiliation>Cisco</affiliation>
      <salary>67000</salary>
    </parent>
  </parents>
  <xmasBoxes>
    <xmasBox>
      <toy>PlayStation</toy>
      <giveRef>1</giveRef>
      <receiveRef>3</receiveRef>
    </xmasBox>
    <xmasBox>
      <toy>Gift card</toy>
      <giveRef>2</giveRef>
      <receiveRef>4</receiveRef>
    </xmasBox>
    <xmasBox>
      <toy>Pencils</toy>
      <giveRef>3</giveRef>
      <receiveRef>2</receiveRef>
    </xmasBox>
    <xmasBox>
      <toy>Puppet</toy>
      <giveRef>4</giveRef>
      <receiveRef>9</receiveRef>
    </xmasBox>
  </xmasBoxes>
  <phoneNumbers>
    <phoneNumber>
      <type>Home</type>
      <number>201-0001</number>
      <parentRefId>201</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Work</type>
      <number>202-0001</number>
      <parentRefId>202</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Cell</type>
      <number>202-0002</number>
      <parentRefId>202</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Home</type>
      <number>203-0001</number>
      <parentRefId>203</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Cell</type>
      <number>203-0002</number>
      <parentRefId>203</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Work</type>
      <number>204-0001</number>
      <parentRefId>204</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Work</type>
      <number>205-0001</number>
      <parentRefId>205</parentRefId>
    </phoneNumber>
    <phoneNumber>
      <type>Work</type>
      <number>206-0001</number>
      <parentRefId>206</parentRefId>
    </phoneNumber>
  </phoneNumbers>
  <SBPS>
    <schedule>
      <location>Location 2</location>
      <time>MonWed</time>
      <childRef>2</childRef>
    </schedule>
    <schedule>
      <location>Location 3</location>
      <time>MonTueWed</time>
      <childRef>3</childRef>
    </schedule>
    <schedule>
      <location>Location 4</location>
      <time>TueFri</time>
      <childRef>4</childRef>
    </schedule>
    <schedule>
      <location>Location 9</location>
      <time>MonWedSat</time>
      <childRef>9</childRef>
    </schedule>
  </SBPS>
</childrenDB>
