=== alexmemory/spicy/spicyEngine/misc/resources/egds/nestedEgdHobby/nestedEgd-target.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Target">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cities" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="city" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" nillable="false" type="xs:string"/>
                                        <xs:element name="companyset" nillable="false">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="company" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="cId" nillable="false" type="xs:string"/>
                                                                <xs:element name="name" nillable="false" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>    
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
          
        
                <xs:element name="personset" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="person" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ssn" nillable="false" type="xs:string"/>
                                        <xs:element name="name" nillable="false" type="xs:string"/>
                                        <xs:element name="salary" nillable="false" type="xs:string"/>
                                        <xs:element name="address" nillable="false" type="xs:string"/>
                                        <xs:element name="companyId" nillable="false" type="xs:string"/>
                                        <xs:element name="hobbyset" nillable="false">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hobby" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="description" nillable="false" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="key1">
            <xs:selector xpath=".//person"/>
            <xs:field xpath="ssn"/>
        </xs:key>
        <xs:key name="key2">
            <xs:selector xpath=".//companyset/company"/>
            <xs:field xpath="cId"/>
        </xs:key>
        <xs:key name="key3">
            <xs:selector xpath=".//companyset/company"/>
            <xs:field xpath="name"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== alexmemory/spicy/spicyEngine/misc/resources/egds/nestedEgdSports/nestedEgd-source-instance-expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<Target xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="nestedEgd-target.xsd">
    <cities>
        <city>
            <name>Seattle</name>
            <companyset>
                <company>
                    <cId>N_1</cId>
                    <name>SJSU</name>
                </company>
                <company>
                    <cId>N_2</cId>
                    <name>IBM</name>
                </company>
            </companyset>
        </city>
        <city>
            <name>Cupertino</name>
            <companyset>
                <company>
                    <cId>N_3</cId>
                    <name>Apple</name>
                </company>
            </companyset>
        </city>
    </cities>
    <personset>
        <person>
            <ssn>1</ssn>
            <name>Alice</name>
            <salary>1000</salary>
            <address>NULL</address>
            <companyId>N_1</companyId>
            <hobbyset>
                <hobby>
                    <description>Music</description>
                </hobby>
            </hobbyset>
        </person>
        <person>
            <ssn>2</ssn>
            <name>John</name>
            <salary>1500</salary>
            <address>NULL</address>
            <companyId>N_2</companyId>
            <hobbyset/>
        </person>
        <person>
            <ssn>3</ssn>
            <name>Mark</name>
            <salary>2000</salary>
            <address>NULL</address>
            <companyId>N_1</companyId>
            <hobbyset>
                <hobby>
                    <description>Soccer</description>
                </hobby>
            </hobbyset>
        </person>
        <person>
            <ssn>4</ssn>
            <name>Steve</name>
            <salary>10000</salary>
            <address>NULL</address>
            <companyId>N_3</companyId>
            <hobbyset/>
        </person>
        <person>
            <ssn>5</ssn>
            <name>Jack</name>
            <salary>NULL</salary>
            <address>NULL</address>
            <companyId>NULL</companyId>
            <hobbyset>
                <hobby>
                    <description>Rugby</description>
                </hobby>
                <hobby>
                    <description>Dance</description>
                </hobby>
            </hobbyset>
        </person>
    </personset>
</Target>
