=== alexmemory/spicy/spicyVerifier/misc/resources/statDBPublicWorksExpenseDB/expenseDB.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="expenseDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="companies" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="company" maxOccurs="unbounded" minOccurs="0" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="companyId" nillable="false" type="xs:string"/>
                    <xs:element name="companyName" nillable="false" type="xs:string"/>
                    <xs:element name="city" nillable="false" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="projects" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="project" maxOccurs="unbounded" minOccurs="0" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="projectId" nillable="false" type="xs:string"/>
                    <xs:element name="projectName" nillable="false" type="xs:string"/>
                    <xs:element name="year" nillable="false" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="grants" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="grant" maxOccurs="unbounded" minOccurs="0" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="principalInvestigator" nillable="false" type="xs:string"/>
                    <xs:element name="amount" nillable="false" type="xs:string"/>
                    <xs:element name="sponsorId" nillable="false" type="xs:string"/>
                    <xs:element name="projectRef" nillable="false" type="xs:string"/>
                    <xs:element name="grantee" nillable="false" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath=".//project"/>
      <xs:field xpath="projectId"/>
    </xs:key>
    <xs:key name="key2">
      <xs:selector xpath=".//company"/>
      <xs:field xpath="companyId"/>
    </xs:key>
    <xs:keyref name="keyRef1" refer="key1">
      <xs:selector xpath=".//grant"/>
      <xs:field xpath="projectRef"/>
    </xs:keyref>
    <xs:keyref name="keyRef2" refer="key2">
      <xs:selector xpath=".//grant"/>
      <xs:field xpath="grantee"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== alexmemory/spicy/spicyVerifier/misc/resources/statDBPublicWorksExpenseDB/expenseDB-instance1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<expenseDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expenseDB.xsd">
  <companies>
    <company>
      <companyId>1</companyId>
      <companyName>Microsoft</companyName>
      <city>Seattle</city>
    </company>
    <company>
      <companyId>2</companyId>
      <companyName>IBM</companyName>
      <city>New York</city>
    </company>
    <company>
      <companyId>3</companyId>
      <companyName>Apple</companyName>
      <city>New England</city>
    </company>
    <company>
      <companyId>4</companyId>
      <companyName>IS Business</companyName>
      <city>Madrid</city>
    </company>
    <company>
      <companyId>5</companyId>
      <companyName>Netech</companyName>
      <city>Milan</city>
    </company>
    <company>
      <companyId>6</companyId>
      <companyName>Alitalia</companyName>
      <city>Rome</city>
    </company>
    <company>
      <companyId>7</companyId>
      <companyName>TrenItalia</companyName>
      <city>Florence</city>
    </company>
    <company>
      <companyId>8</companyId>
      <companyName>Intema</companyName>
      <city>Washington</city>
    </company>
    <company>
      <companyId>9</companyId>
      <companyName>Publisys</companyName>
      <city>Potenza</city>
    </company>
    <company>
      <companyId>10</companyId>
      <companyName>Carapelli</companyName>
      <city>Tunis</city>
    </company>
    <company>
      <companyId>11</companyId>
      <companyName>Barilla</companyName>
      <city>Naples</city>
    </company>
    <company>
      <companyId>12</companyId>
      <companyName>Bayer</companyName>
      <city>Budapest</city>
    </company>
    <company>
      <companyId>13</companyId>
      <companyName>Fineco</companyName>
      <city>York</city>
    </company>
    <company>
      <companyId>14</companyId>
      <companyName>CK</companyName>
      <city>Naples</city>
    </company>
    <company>
      <companyId>15</companyId>
      <companyName>EF Tourism</companyName>
      <city>Padova</city>
    </company>
    <company>
      <companyId>16</companyId>
      <companyName>Universal</companyName>
      <city>Venice</city>
    </company>
    <company>
      <companyId>17</companyId>
      <companyName>Nikon</companyName>
      <city>Belgrado</city>
    </company>
    <company>
      <companyId>18</companyId>
      <companyName>Cinco</companyName>
      <city>Dubai</city>
    </company>
    <company>
      <companyId>19</companyId>
      <companyName>Siesta</companyName>
      <city>Barcelona</city>
    </company>
    <company>
      <companyId>20</companyId>
      <companyName>UK Tourism</companyName>
      <city>London</city>
    </company>
    <company>
      <companyId>21</companyId>
      <companyName>MasterMind</companyName>
      <city>Cambridge</city>
    </company>
    <company>
      <companyId>22</companyId>
      <companyName>Art Holiday</companyName>
      <city>Manchester</city>
    </company>
    <company>
      <companyId>23</companyId>
      <companyName>TNT</companyName>
      <city>Paris</city>
    </company>
    <company>
      <companyId>24</companyId>
      <companyName>Russian EF</companyName>
      <city>Moscow</city>
    </company>
    <company>
      <companyId>25</companyId>
      <companyName>Chang Lie</companyName>
      <city>Tokyo</city>
    </company>
    <company>
      <companyId>26</companyId>
      <companyName>Hong Kong Board,</companyName>
      <city>Hong Kong</city>
    </company>
    <company>
      <companyId>27</companyId>
      <companyName>Picture Photo</companyName>
      <city>Dublin</city>
    </company>
    <company>
      <companyId>28</companyId>
      <companyName>Math World</companyName>
      <city>Malta</city>
    </company>
    <company>
      <companyId>29</companyId>
      <companyName>Esperando</companyName>
      <city>Standford</city>
    </company>
    <company>
      <companyId>30</companyId>
      <companyName>HTG</companyName>
      <city>Adrian</city>
    </company>
    <company>
      <companyId>31</companyId>
      <companyName>EDP Software</companyName>
      <city>Amsterdam</city>
    </company>
    <company>
      <companyId>32</companyId>
      <companyName>CT Solutions</companyName>
      <city>Jerusalem</city>
    </company>
    <company>
      <companyId>33</companyId>
      <companyName>Old Times</companyName>
      <city>Purdue</city>
    </company>
    <company>
      <companyId>34</companyId>
      <companyName>ABC</companyName>
      <city>New Orleans</city>
    </company>
    <company>
      <companyId>35</companyId>
      <companyName>Software Enterprise</companyName>
      <city>Tel Aviv</city>
    </company>
    <company>
      <companyId>36</companyId>
      <companyName>Top Universal</companyName>
      <city>Siena</city>
    </company>
    <company>
      <companyId>37</companyId>
      <companyName>Rikiko</companyName>
      <city>Tokyo</city>
    </company>
    <company>
      <companyId>38</companyId>
      <companyName>Oscar</companyName>
      <city>Madrid</city>
    </company>
    <company>
      <companyId>39</companyId>
      <companyName>North Force</companyName>
      <city>Hong Kong</city>
    </company>
    <company>
      <companyId>40</companyId>
      <companyName>South Force</companyName>
      <city>Prague</city>
    </company>
    <company>
      <companyId>41</companyId>
      <companyName>Rio Software</companyName>
      <city>Cambridge</city>
    </company>
    <company>
      <companyId>42</companyId>
      <companyName>Art Gallery</companyName>
      <city>Vienna</city>
    </company>
    <company>
      <companyId>43</companyId>
      <companyName>ICT Record</companyName>
      <city>Manchester</city>
    </company>
    <company>
      <companyId>44</companyId>
      <companyName>EF Enterprise</companyName>
      <city>Berlin</city>
    </company>
    <company>
      <companyId>45</companyId>
      <companyName>EDB Solutions</companyName>
      <city>San Francisco</city>
    </company>
    <company>
      <companyId>46</companyId>
      <companyName>CIS Programs,</companyName>
      <city>Paris</city>
    </company>
    <company>
      <companyId>47</companyId>
      <companyName>Math Analysis</companyName>
      <city>Oslo</city>
    </company>
    <company>
      <companyId>48</companyId>
      <companyName>Math Scientists</companyName>
      <city>Tirane</city>
    </company>
    <company>
      <companyId>49</companyId>
      <companyName>Rionill</companyName>
      <city>Bruxelles</city>
    </company>
    <company>
      <companyId>50</companyId>
      <companyName>Refill</companyName>
      <city>Belgrado</city>
    </company>
  </companies>
  <projects>
    <project>
      <projectId>1</projectId>
      <projectName>SQL Server</projectName>
      <year>1980</year>
    </project>
    <project>
      <projectId>2</projectId>
      <projectName>DB2</projectName>
      <year>1980</year>
    </project>
    <project>
      <projectId>3</projectId>
      <projectName>Clio</projectName>
      <year>2000</year>
    </project>
    <project>
      <projectId>4</projectId>
      <projectName>Windows</projectName>
      <year>1980</year>
    </project>
    <project>
      <projectId>5</projectId>
      <projectName>Logos</projectName>
      <year>1990</year>
    </project>
    <project>
      <projectId>6</projectId>
      <projectName>Wiki</projectName>
      <year>2000</year>
    </project>
    <project>
      <projectId>7</projectId>
      <projectName>Peers</projectName>
      <year>2001</year>
    </project>
    <project>
      <projectId>8</projectId>
      <projectName>Simbian</projectName>
      <year>2002</year>
    </project>
    <project>
      <projectId>9</projectId>
      <projectName>Marking</projectName>
      <year>2003</year>
    </project>
    <project>
      <projectId>10</projectId>
      <projectName>Label</projectName>
      <year>2004</year>
    </project>
    <project>
      <projectId>11</projectId>
      <projectName>Process</projectName>
      <year>2005</year>
    </project>
    <project>
      <projectId>12</projectId>
      <projectName>Evaluation 8</projectName>
      <year>2006</year>
    </project>
    <project>
      <projectId>13</projectId>
      <projectName>Excalibur</projectName>
      <year>2000</year>
    </project>
    <project>
      <projectId>14</projectId>
      <projectName>Redies</projectName>
      <year>1990</year>
    </project>
    <project>
      <projectId>15</projectId>
      <projectName>Runner</projectName>
      <year>1999</year>
    </project>
    <project>
      <projectId>16</projectId>
      <projectName>IWL Project</projectName>
      <year>1998</year>
    </project>
    <project>
      <projectId>17</projectId>
      <projectName>Mokami</projectName>
      <year>2000</year>
    </project>
    <project>
      <projectId>18</projectId>
      <projectName>Irc</projectName>
      <year>2001</year>
    </project>
    <project>
      <projectId>19</projectId>
      <projectName>NetWire</projectName>
      <year>2005</year>
    </project>
    <project>
      <projectId>20</projectId>
      <projectName>Previous</projectName>
      <year>2001</year>
    </project>
    <project>
      <projectId>21</projectId>
      <projectName>Pass 123</projectName>
      <year>2000</year>
    </project>
    <project>
      <projectId>22</projectId>
      <projectName>Wireless</projectName>
      <year>1997</year>
    </project>
    <project>
      <projectId>23</projectId>
      <projectName>Meeting</projectName>
      <year>1989</year>
