=== alexmemory/spicy/spicyEngine/misc/resources/egds/personCarCity/personCarCity-source.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PersonCarCitySource">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PersonCarSet1" minOccurs="1" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PersonCar1" maxOccurs="unbounded" minOccurs="1" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="personName" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="age" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="carPlate" minOccurs="1" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PersonCarSet2" minOccurs="1" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PersonCar2" maxOccurs="unbounded" minOccurs="1" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="personName" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="carModel" minOccurs="1" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PersonCitySet" minOccurs="1" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PersonCity" maxOccurs="unbounded" minOccurs="1" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="personName" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="cityName" minOccurs="1" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CarMakeSet" minOccurs="1" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CarMake" maxOccurs="unbounded" minOccurs="1" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="carModel" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="makeName" minOccurs="1" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CityRegionSet" minOccurs="1" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="City" maxOccurs="unbounded" minOccurs="1" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cityName" minOccurs="1" nillable="true" type="xs:string"/>
                                        <xs:element name="region" minOccurs="1" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="keyPersonCar1">
            <xs:selector xpath=".//PersonCar1"/>
            <xs:field xpath="personName"/>
        </xs:key>
        <xs:key name="keyPersonCar2">
            <xs:selector xpath=".//PersonCar2"/>
            <xs:field xpath="personName"/>
        </xs:key>
        <xs:key name="keyPersonCity">
            <xs:selector xpath=".//PersonCity"/>
            <xs:field xpath="personName"/>
        </xs:key>
        <xs:key name="keyCarMake">
            <xs:selector xpath=".//CarMake"/>
            <xs:field xpath="carModel"/>
        </xs:key>
        <xs:key name="keyCity">
            <xs:selector xpath=".//City"/>
            <xs:field xpath="cityName"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== alexmemory/spicy/spicyEngine/misc/resources/egds/personCarCity/personCarCity-source-instance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PersonCarCitySource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personCarCity-source.xsd">
    <PersonCarSet1>
        <PersonCar1>
            <personName>John</personName>
            <age>18</age>
            <carPlate>AB1234</carPlate>
        </PersonCar1>
        <PersonCar1>
            <personName>Frank</personName>
            <age>21</age>
            <carPlate>AC5678</carPlate>
        </PersonCar1>
    </PersonCarSet1>
    <PersonCarSet2>
        <PersonCar2>
            <personName>John</personName>
            <carModel>Punto</carModel>
        </PersonCar2>
        <PersonCar2>
            <personName>Mark</personName>
            <carModel>Fiesta</carModel>
        </PersonCar2>
    </PersonCarSet2>
    <PersonCitySet>
        <PersonCity>
            <personName>John</personName>
            <cityName>Roma</cityName>
        </PersonCity>
        <PersonCity>
            <personName>Anthony</personName>
            <cityName>Milano</cityName>
        </PersonCity>
    </PersonCitySet>
    <CarMakeSet>
        <CarMake>
            <carModel>Punto</carModel>
            <makeName>Fiat</makeName>
        </CarMake>
        <CarMake>
            <carModel>Corolla</carModel>
            <makeName>Toyota</makeName>
        </CarMake>
    </CarMakeSet>
    <CityRegionSet>
        <City>
            <cityName>Roma</cityName>
            <region>Lazio</region>
        </City>
        <City>
            <cityName>Milano</cityName>
            <region>Lombardia</region>
        </City>
    </CityRegionSet>
</PersonCarCitySource>
