=== alexmemory/spicy/spicyGUI/spicygui/schemas/statDB.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="statDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="cityStat" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" name="city" nillable="false" type="xs:string"/>
              <xs:element minOccurs="1" name="organizations" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="organization" nillable="false">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" name="companyId" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="companyName" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="0" name="fundings" nillable="false">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" minOccurs="0" name="fund" nillable="false">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element minOccurs="1" name="principalInvestigator" nillable="false" type="xs:string"/>
                                      <xs:element minOccurs="1" name="financialIdRef" nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" name="financials" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="financial" nillable="false">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" name="financialId" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="amount" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="project" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="year" nillable="false" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" name="programs" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="program" nillable="false">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" name="startYear" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="endYear" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="budget" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="programName" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="companyRef" nillable="false" type="xs:string"/>
                          <xs:element minOccurs="1" name="director" nillable="false" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath=".//financial"/>
      <xs:field xpath="financialId"/>
    </xs:key>
    <xs:key name="key2">
      <xs:selector xpath=".//organization"/>
      <xs:field xpath="companyId"/>
    </xs:key>
    <xs:keyref name="keyRef1" refer="key1">
      <xs:selector xpath=".//fund"/>
      <xs:field xpath="financialIdRef"/>
    </xs:keyref>
    <xs:keyref name="keyRef2" refer="key2">
      <xs:selector xpath=".//program"/>
      <xs:field xpath="companyRef"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== alexmemory/spicy/spicyGUI/spicygui/schemas/statDB-instance1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<statDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="statDB.xsd">
  <cityStat>
    <city>New York</city>
    <organizations>
      <organization>
        <companyId>1</companyId>
        <companyName>IBM</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Frank Miller</principalInvestigator>
            <financialIdRef>101</financialIdRef>
          </fund>
          <fund>
            <principalInvestigator>Neal Adams</principalInvestigator>
            <financialIdRef>102</financialIdRef>
          </fund>
        </fundings>
      </organization>
    </organizations>
    <financials>
      <financial>
        <financialId>101</financialId>
        <amount>1000.0</amount>
        <project>Clio</project>
        <year>2000</year>
      </financial>
      <financial>
        <financialId>102</financialId>
        <amount>5000.0</amount>
        <project>DB2</project>
        <year>1980</year>
      </financial>
    </financials>
    <programs>
      <program>
        <startYear>1990</startYear>
        <endYear>2000</endYear>
        <budget>3500.0</budget>
        <programName>Program</programName>
        <companyRef>1</companyRef>
        <director>Joseph De Nicolas</director>
      </program>
      <program>
        <startYear>1981</startYear>
        <endYear>2007</endYear>
        <budget>5500.0</budget>
        <programName>ABC WORLD</programName>
        <companyRef>1</companyRef>
        <director>Mary Luois</director>
      </program>
      <program>
        <startYear>1993</startYear>
        <endYear>2001</endYear>
        <budget>13500.0</budget>
        <programName>TESTING</programName>
        <companyRef>1</companyRef>
        <director>Lucy Andy</director>
      </program>
    </programs>
  </cityStat>
  <cityStat>
    <city>Seattle</city>
    <organizations>
      <organization>
        <companyId>2</companyId>
        <companyName>Microsoft</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Stan Lee</principalInvestigator>
            <financialIdRef>103</financialIdRef>
          </fund>
        </fundings>
      </organization>
      <organization>
        <companyId>3</companyId>
        <companyName>Boing</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Steve Ditko</principalInvestigator>
            <financialIdRef>104</financialIdRef>
          </fund>
        </fundings>
      </organization>
    </organizations>
    <financials>
      <financial>
        <financialId>103</financialId>
        <amount>1000.0</amount>
        <project>SQL Server</project>
        <year>1980</year>
      </financial>
      <financial>
        <financialId>104</financialId>
        <amount>1500.0</amount>
        <project>B530</project>
        <year>2006</year>
      </financial>
      <financial>
        <financialId>105</financialId>
        <amount>2000.0</amount>
        <project>Dummy Financial</project>
        <year>2006</year>
      </financial>
    </financials>
    <programs>
      <program>
        <startYear>1990</startYear>
        <endYear>2000</endYear>
        <budget>3500.0</budget>
        <programName>Program</programName>
        <companyRef>2</companyRef>
        <director>Gerard McQuine</director>
      </program>
      <program>
        <startYear>1991</startYear>
        <endYear>2007</endYear>
        <budget>5500.0</budget>
        <programName>Excalibur</programName>
        <companyRef>2</companyRef>
        <director>Andrew Paine</director>
      </program>
      <program>
        <startYear>1983</startYear>
        <endYear>2001</endYear>
        <budget>13500.0</budget>
        <programName>WorldWide</programName>
        <companyRef>3</companyRef>
        <director>Giselle Dolores</director>
      </program>
    </programs>
  </cityStat>
  <cityStat>
    <city>Rome</city>
    <organizations>
      <organization>
        <companyId>6</companyId>
        <companyName>Reverting</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Tim Pink</principalInvestigator>
            <financialIdRef>1001</financialIdRef>
          </fund>
          <fund>
            <principalInvestigator>Marian Bloskin</principalInvestigator>
            <financialIdRef>1002</financialIdRef>
          </fund>
        </fundings>
      </organization>
    </organizations>
    <financials>
      <financial>
        <financialId>1001</financialId>
        <amount>1000.0</amount>
        <project>Craft</project>
        <year>1999</year>
      </financial>
      <financial>
        <financialId>1002</financialId>
        <amount>5000.0</amount>
        <project>Miami</project>
        <year>1980</year>
      </financial>
    </financials>
    <programs>
      <program>
        <startYear>1990</startYear>
        <endYear>2000</endYear>
        <budget>13500.0</budget>
        <programName>Program</programName>
        <companyRef>6</companyRef>
        <director>Dino Mancini</director>
      </program>
      <program>
        <startYear>1991</startYear>
        <endYear>2007</endYear>
        <budget>5500.0</budget>
        <programName>Excalibur</programName>
        <companyRef>6</companyRef>
        <director>Bill Clinton</director>
      </program>
      <program>
        <startYear>1992</startYear>
        <endYear>2003</endYear>
        <budget>1500.0</budget>
        <programName>WorldWide</programName>
        <companyRef>6</companyRef>
        <director>Gino Selvaggi</director>
      </program>
    </programs>
  </cityStat>
  <cityStat>
    <city>Florence</city>
    <organizations>
      <organization>
        <companyId>7</companyId>
        <companyName>Red Mountain</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Priam Prori</principalInvestigator>
            <financialIdRef>1101</financialIdRef>
          </fund>
          <fund>
            <principalInvestigator>Erich Siani</principalInvestigator>
            <financialIdRef>1102</financialIdRef>
          </fund>
        </fundings>
      </organization>
    </organizations>
    <financials>
      <financial>
        <financialId>1101</financialId>
        <amount>1000.0</amount>
        <project>W3C</project>
        <year>2000</year>
      </financial>
      <financial>
        <financialId>1102</financialId>
        <amount>5000.0</amount>
        <project>Broad Board</project>
        <year>1980</year>
      </financial>
    </financials>
    <programs>
      <program>
        <startYear>1999</startYear>
        <endYear>2000</endYear>
        <budget>13500.0</budget>
        <programName>Programming</programName>
        <companyRef>7</companyRef>
        <director>Peter Ball</director>
      </program>
      <program>
        <startYear>1971</startYear>
        <endYear>2007</endYear>
        <budget>5500.0</budget>
        <programName>WorldCup</programName>
        <companyRef>7</companyRef>
        <director>Moby Parker</director>
      </program>
      <program>
        <startYear>1982</startYear>
        <endYear>2003</endYear>
        <budget>1500.0</budget>
        <programName>B2B Consumer</programName>
        <companyRef>7</companyRef>
        <director>Tony Stark</director>
      </program>
    </programs>
  </cityStat>
  <cityStat>
    <city>Paris</city>
    <organizations>
      <organization>
        <companyId>8</companyId>
        <companyName>Happy Week</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Peter Sarli</principalInvestigator>
            <financialIdRef>1201</financialIdRef>
          </fund>
          <fund>
            <principalInvestigator>James Smith</principalInvestigator>
            <financialIdRef>1202</financialIdRef>
          </fund>
        </fundings>
      </organization>
    </organizations>
    <financials>
      <financial>
        <financialId>1201</financialId>
        <amount>3000.0</amount>
        <project>White Paper</project>
        <year>1993</year>
      </financial>
      <financial>
        <financialId>1202</financialId>
        <amount>6000.0</amount>
        <project>Rich World</project>
        <year>1989</year>
      </financial>
    </financials>
    <programs>
      <program>
        <startYear>1999</startYear>
        <endYear>2000</endYear>
        <budget>13500.0</budget>
        <programName>Picture Image</programName>
        <companyRef>8</companyRef>
        <director>Peter Sarli</director>
      </program>
      <program>
        <startYear>1971</startYear>
        <endYear>2007</endYear>
        <budget>5500.0</budget>
        <programName>World Cup</programName>
        <companyRef>8</companyRef>
        <director>Tim Brown</director>
      </program>
      <program>
        <startYear>1982</startYear>
        <endYear>2003</endYear>
        <budget>1500.0</budget>
        <programName>BBC Lumen</programName>
        <companyRef>8</companyRef>
        <director>Erich Clapton</director>
      </program>
    </programs>
  </cityStat>
  <cityStat>
    <city>Vienna</city>
    <organizations>
      <organization>
        <companyId>9</companyId>
        <companyName>Yoyo</companyName>
        <fundings>
          <fund>
            <principalInvestigator>Tim Black</principalInvestigator>
            <financialIdRef>1301</financialIdRef>
          </fund>
          <fund>
            <principalInvestigator>Brian White</principalInvestigator>
            <financialIdRef>1302</financialIdRef>
          </fund>
        </fundings>
